name: example
description: This is a simple bpe tokenizer for use with OpenAI's models.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-275.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  equatable: ^2.0.5
  sp_ai_simple_bpe_tokenizer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
