name: sp_ai_simple_bpe_tokenizer
description: This is a simple bpe tokenizer for use with OpenAI's models.
version: 0.0.1+2
homepage: https://github.com/Theunodb/Spaza-AI-Simple-BPE-Tokenizer

environment:
    sdk: ">=2.19.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/
    - assets/files/
    - assets/files/encoder.json
    - assets/files/vocab.bpe
